### PR TITLE
PR to fix https://github.com/NIH-HPC/gpu4singularity/issues/1

### LINKED ISSUE #1: Ask for new features
Hi,

This script is very useful, but it actually works only for the NIH Biowulf cluster.

I have done some modifications and I will send a PR relative to this issue.

So basically, I want to :
  - be able to specify the NVIDIA driver version
  - be able to specify another download link
  - be able to specify if I am using the .run file provided by NVIDIA or a file already extracted once (see `--extract` and `--extract-only` for the last archive).

I would also like to change `./tmp` filename created to overwrite `/environment` which seems a bit confusing for me, to something like `./tmp_env`. Moreover, I am getting an issue using `./tmp` (I do not remember why exactly).

Best regards,
Rémy

### PR DESCRIPTION
**Pull request by remyd1**
Fixes #1

Changes proposed in this pull request

Options to specify:
  - if the NVIDIA .run file has been already extracted
  - a different download URL
  - another version

@NIH-HPC-admin

Rémy

### CODE REVIEW

**Comment by GodloveD** [comment]
Hi @remyd1 .  Thanks very much for suggesting these changes!  Overall they look great.  I do have one question though about the `--not-already-extracted` option.  I don't really understand what that means.  When I try to call the `.run` file on our ftp site with that syntax, I get an error:
```
$ mkdir blah
$ ./NVIDIA-Linux-x86_64-367.48.run -extract=blah
Verifying archive integrity... OK
Uncompressing NVIDIA Accelerated Graphics Driver for Linux-x86_64 367.48..................................................................................................................................................................................................................................................................................................
./nvidia-installer: unrecognized option: "-extract"

ERROR: Invalid commandline, please run `./nvidia-installer --help` for usage information.

```
Can you clarify?  Does this work with later versions of the `.run` installer?

**Comment by remyd1** [comment]
Hello @GodloveD,

Yes, that's exactly what this means.
Indeed, you can check with the last release on the nvidia website or take a look on the one I am hosting here: ftp://ngsisem.mbb.univ-montp2.fr/mbbteam/datadir/NVIDIA-Linux-x86_64-375.26.run

I renamed it to match the second archive filename.

The `--extract` option is avalaible on the first archive and `--extract-only` is only avalaible in the second archive. When I [download the .run file from NVIDIA](https://developer.nvidia.com/compute/cuda/8.0/Prod2/local_installers/cuda_8.0.61_375.26_linux-run), that's what I get.

```
sh ./cuda_8.0.61_375.26_linux.run --help
  ....
  --extract=<path>
    Extracts the individual driver, toolkit, and samples runfile installers
    to <path>.
   ....
```

eg:
```
sh ./cuda_8.0.61_375.26_linux.run --extract=/tmp/
ls /tmp
-rwxrwxr-x  1 remy remy  101033340 avril  6 10:37 cuda-samples-linux-8.0.61-21551265.run
-rwxrwxr-x  1 remy remy 1292835953 avril  6 10:37 cuda-linux64-rel-8.0.61-21551265.run
-rwxrwxr-x  1 remy remy   75869960 avril  6 10:37 NVIDIA-Linux-x86_64-375.26.run
...
cd /tmp
sh NVIDIA-Linux-x86_64-375.26.run --help
  ...
-x, --extract-only
  Extract the contents of NVIDIA-Linux-x86_64-375.26.run, but do not
  run 'nvidia-installer'.
  ...
```

And then, you have the right .run file with good filename format.

Rémy

**Comment by GodloveD** [comment]
OK, that makes sense.  I agree that it is useful and desirable to be able to install the NVIIDA driver from either a driver .run file or from a CUDA .run file.  But I think the option wording is a little confusing.  It's possible that a user would download a .run file that doesn't have CUDA and doesn't need 2 levels of extraction.  But they have technically not extracted anything, so the --not-already-extracted option might sound like the right thing to do (even though it will break).

How about something more like this?
```
        -c, --from-cuda
                Extract the nvidia<version>.run file and install drivers 
                from a cuda<version>.run archive bundle.  
```

**Comment by remyd1** [comment]
Ok, that is a good idea. I will modify it as soon as I can.

**Comment by GodloveD** [comment]
@remyd1 Last changes look good.  This pull-request is a big improvement.  Thanks again!

**Pull request merged**
