### PR TITLE
2.3support

### LINKED ISSUE #3: 2.3 is not supported
This is broken because the way you set up the environment changed in 2.3.

### PR DESCRIPTION
**Pull request by GodloveD**
Fixes #3 

Changes proposed in this pull request

 - now we will either write to `/.singularity.d/env` or `/environment` depending on what version of singularity we detect.  

@NIH-HPC-admin

### CODE REVIEW

**Comment by 0xaf1f** [comment]
Hey, @GodloveD, I had tried converting your status to "collaborator" so that you'd retain write access, but Github apparently just removed you completely.

Also, is it worth maintaining this for 2.3+ given the existence of the `--nv` option?

**Comment by GodloveD** [comment]
Maybe and maybe not.  Have you been watching the general channel of the Singularity slack today?  It might help with compiling some gpu code a bootstrap time, but then again it might be unnecessary.  

I think I'd like to keep it working.  In the future I might try some experiments with creating more thorough directory hierarchies and using `ld.cache` so it might be nice to be able to use this script.

**Comment by 0xaf1f** [comment]
Ok, I see.

And figured out that collaborator status is on a per-repository basis, so I invited you as such for this one and your tutorial repo. Feel free to push at will.

**Comment by GodloveD** [comment]
Thanks for sending the invite to collaborate @0xaf1f !  😸

**Comment by 0xaf1f** [comment]
It was the least I could do :wink:

**Comment by 0xaf1f** [comment]
And thanks for continuing to care for this!

**Pull request merged**
